// src/app/carte/page.tsx
import { CenteredText, Header, Title } from "@/components";
import { BISE, LESAUVAGE, MONGYTRIPLE, QUIDAM, SPECIALE } from "@/data/beers";
import {
  AMARETTOSOUR,
  BerryPlease,
  Daiquiri,
  DarkAndStormy,
  EspressoMartini,
  FrenchMargarita,
  Gimlet,
  GrannyDaddy,
  Mocktail,
  Negroni,
  OliveDryMartini,
  Paloma,
  Penicillin,
  VieuxCarré,
} from "@/data/cocktails";
import { Metadata } from "next";
import Link from "next/link";
import { Cocktail } from "../cocktails/Cocktail";
import { euro } from "@/utils/money";
import { WINES } from "@/data/wine";
import { SPIRITS } from "@/data/spirits";
import { SOFTS } from "@/data/soft";
import { COFFEE } from "@/data/coffee";
import { Product } from "@/components/Product";

export const metadata: Metadata = {
  title: "Alices | La Carte",
  description:
    "Café torréfié à Lille, vins natures et surprenants, bières locales, cocktails délicieux, large gamme de softs et tartinables faits sur place",
};

export default function () {
  return (
    <div className="flex flex-col gap-8">
      <Block>
        <Header>
          <Title>Bières pression</Title>
          <span className="whitespace-nowrap">25, 33 ou 50cl</span>
        </Header>

        <ul>
          {[BISE, QUIDAM, LESAUVAGE, MONGYTRIPLE, SPECIALE].map((beer) => {
            return (
              <li key={beer.label}>
                <Product
                  key={beer.label}
                  label={beer.label}
                  description={beer.brewery}
                  price={beer.price}
                />
              </li>
            );
          })}
        </ul>
      </Block>

      <Block>
        <Header>
          <Title>Bières Bouteilles</Title>
        </Header>

        <CenteredText>
          🍾🥫🍺🥫🍾
          <br />
          Notre sélection de bières bouteilles <br /> et canettes craft <br />{" "}
          avec des options sans alcool & sans gluten <br /> est à retrouver
          directement au bar <br />
          🍺🥫🍾🥫🍺
        </CenteredText>
      </Block>

      <Block>
        <Header>
          <Title>Vin</Title>
          <span className="whitespace-nowrap">Au verre ou en bouteille</span>
        </Header>
        {WINES.map((wine) => {
          return (
            <Product
              key={wine.label}
              label={wine.label}
              description={wine.description}
              price={wine.price}
            />
          );
        })}
      </Block>

      <Block>
        <Header>
          <Title>Cocktails</Title>
        </Header>

        <div>
          <ul className="flex flex-col gap-2">
            {[
              Mocktail,
              GrannyDaddy,
              BerryPlease,
              Gimlet,
              AMARETTOSOUR,
              OliveDryMartini,
              Daiquiri,
              Negroni,
              DarkAndStormy,
              FrenchMargarita,
              Paloma,
              EspressoMartini,
              Penicillin,
              VieuxCarré,
            ].map((cocktail) => {
              return (
                <li key={cocktail.label}>
                  <Cocktail {...cocktail} />
                </li>
              );
            })}
          </ul>
        </div>

        <div>
          <ul>
            <li>🌱 vegan</li>
            <li>🌶️ spicy</li>
            <li>😇 virgin</li>
          </ul>
        </div>

        <div className="flex justify-between">
          <span>🍸🥂🥃🍹</span>
          <Link href="/cocktails">Voir tous nos cocktails</Link>
        </div>
      </Block>

      <Block>
        <Header>
          <Title>Shooters</Title>
          <span className="whitespace-nowrap">3.5€ l’unité & 18€ les 6</span>
        </Header>

        <CenteredText>
          🥛🥛🥛🥛🥛🥛
          <br />
          Nos recettes maison changent régulièrement
          <br />
          Viens voir lesjarres au bar !
          <br />
          🥛🥛🥛🥛🥛🥛
        </CenteredText>
      </Block>

      <Block>
        <Header>
          <Title>Spiritueux</Title>
        </Header>

        {SPIRITS.map((spirit) => {
          return (
            <Product
              key={spirit.label}
              label={spirit.label}
              description={spirit.description}
              price={spirit.price}
            />
          );
        })}
      </Block>

      <Block>
        <Header>
          <Title>Soft</Title>
        </Header>

        {SOFTS.map((soft) => {
          return (
            <Product key={soft.label} label={soft.label} price={soft.price} />
          );
        })}
      </Block>

      <Block>
        <Header>
          <Title>Tartinades</Title>
        </Header>
        {[
          {
            label: "Tartinades [120g]",
            price: 7,
          },
          {
            label: "Olives",
            price: 2.5,
          },
        ].map((product) => {
          return (
            <Product
              key={product.label}
              label={product.label}
              price={product.price}
            />
          );
        })}
      </Block>

      <Block>
        <Header>
          <Title>Cafés</Title>
        </Header>
        {COFFEE.map((coffee) => {
          return (
            <Product
              key={coffee.label}
              label={coffee.label}
              description={coffee.description}
              price={coffee.price}
            />
          );
        })}
      </Block>

      <Block>
        <Header>
          <Title>Et pleins d'autres surprises au bar</Title>
        </Header>
      </Block>

      <div className="flex justify-center">
        <picture>
          <source
            srcSet="/icons/cocktail-dark.png"
            media="(prefers-color-scheme: dark)"
          />
          <img src="/icons/cocktail.png" alt="Cocktail" width="40" />
        </picture>
      </div>
    </div>
  );
}

type BlockProps = {
  children: React.ReactNode;
};
const Block = ({ children }: BlockProps) => {
  return <div className="flex flex-col gap-2 text-left">{children}</div>;
};

// src/routes/carte.svelte
<script context="module" lang="ts">
  import { browser } from '$app/env';
  import MenuBlock from '$lib/components/MenuBlock.svelte';
  import Stack from '$lib/components/Stack.svelte';
  import SvelteSeo from 'svelte-seo';

  import Beers from '$lib/components/Beers.svelte';
  import Cocktails from '$lib/components/Cocktails.svelte';
  import Coffee from '$lib/components/Coffee.svelte';
  import Food from '$lib/components/Food.svelte';
  import Shooters from '$lib/components/Shooters.svelte';
  import Softs from '$lib/components/Softs.svelte';
  import Spirits from '$lib/components/Spirits.svelte';
  import Wines from '$lib/components/Wines.svelte';

  import {
    bottles,
    cocktails,
    coffee,
    food,
    softs,
    spirits,
    taps,
    wines,
  } from '$data/menu';
  export const router = browser;
  export const prerender = true;

  const SEO_DESCRIPTION =
    'Café torréfié à Lille, vins natures et surprenants, bières locales, cocktails délicieux, large gamme de softs et tartinables faits sur place';

  const CURRENT_SEASON = 'summer2022';
  const filter = (items) =>
    items.filter(
      (item) =>
        !item.disabled &&
        (item.availability === undefined ||
          item.availability.includes(CURRENT_SEASON))
    );

  const getCocktails = (items: string[]) =>
    items.map((label) => cocktails.find((c) => c.label === label));
</script>

<SvelteSeo
  title="Alices | La Carte"
  description={SEO_DESCRIPTION}
  canonical="https://alices-lille.com/carte"
/>
<picture>
  <source
    srcset="/images/icons/friends-dark.png"
    media="(prefers-color-scheme: dark)"
  />
  <img
    src="/images/icons/friends.png"
    alt="Amis en train de partager des bières et du vin"
    width="120"
  />
</picture>
<br />
<br />

<Stack>
  {#if new Date().getHours() >= 15 && new Date().getHours() <= 17}
    <MenuBlock title="Cafés">
      <Coffee {coffee} />
    </MenuBlock>
  {/if}

  {#if new Date().getDay() === 6 && new Date().getHours() >= 17}
    <MenuBlock title="🍸 Samedi c'est espresso Martini !">
      <Cocktails cocktails={getCocktails(['Espresso Martini'])} />
    </MenuBlock>
  {/if}

  <MenuBlock title="Bières Pression" text="25, 33 ou 50cl">
    <Beers beers={taps} />
  </MenuBlock>

  <MenuBlock title="Bières Bouteilles">
    <Beers beers={bottles} />
  </MenuBlock>

  <MenuBlock title="Vin" text="Au verre ou en bouteille">
    <Wines wines={filter(wines)} />
  </MenuBlock>

  <MenuBlock title="Cocktails">
    <Cocktails
      cocktails={getCocktails([
        'Gin Fizz',
        'Amaretto Sour',
        'Negroni',
        'Gimlet Clémentine',
        'Daiquiri Cacahuète',
        'Dark & stormy',
        'Cosmo',
        'Espresso Martini',
        'Penicilin',
        'Paloma',
        'Irish Coffee (ou  jamaican, french)'
        'Mocktail',
      ])}
    />
  </MenuBlock>

  <div class="text-right text-emphase flex justify-between">
    <div>🍸🥂🥃🍹</div>
    <a href="/cocktails">Voir tous nos cocktails</a>
  </div>
  <br />

  <MenuBlock title="Shooters" text="3.5€ l’unité & 18€ les 6">
    <Shooters />
  </MenuBlock>

  <MenuBlock title="Spiritueux">
    <Spirits spirits={filter(spirits)} />
  </MenuBlock>

  <MenuBlock title="Softs">
    <Softs softs={filter(softs)} />
  </MenuBlock>

  <MenuBlock title="Tartinades">
    <Food {food} />
  </MenuBlock>

  {#if new Date().getHours() < 15 || new Date().getHours() > 17}
    <MenuBlock title="Cafés">
      <Coffee {coffee} />
    </MenuBlock>
  {/if}

  <MenuBlock title="Et pleins d'autres surprises au bar" />

  <picture>
    <source
      srcset="/images/icons/cocktail-dark.png"
      media="(prefers-color-scheme: dark)"
    />
    <img src="/images/icons/cocktail.png" alt="Cocktail" width="40" />
  </picture>
</Stack>
